### ISSUE TITLE
Fluid attributes (e.g. px-xs) aren't generated when they're only present in a CSS @apply statement

### ISSUE THREAD

**Issue by rainypixels** [cwsdigital/tailwind-utopia#3]
When fluid attributes like `px-xs` are in the html, they seem to get generated properly and injected into the CSS. But this doesn't seem to work when the same attribute is moved to an @apply statement in the CSS file. So this works:

```
<span class="more px-xs">More</span>
```

But this doesn't work when it's in the css:
```
.more {
    @apply px-xs;
}
```

I feel like I'm missing something obvious here but I can't seem to figure out what that is. 😬

**Comment by chrispymm** [comment]
Hi again 👋

Is your `@apply` within an `@layer` directive?

This isn't super-obvious from the docs, but JIT mode uses purge to rebuild, and tailwinds purge will only purge things within `@layer` dircetives - this is so that it doesn't remove any styles that aren't tailwind related.

There's a mention of this at the bottom of the [layer docs](https://tailwindcss.com/docs/functions-and-directives#layer) and again in the [purge docs](https://tailwindcss.com/docs/optimizing-for-production#removing-all-unused-styles)

So, taking your example from above, assuming you were trying to create a `.more` utiltity class, you'd want:
```
@layer utilities {
  .more {
    @apply px-xs
  }
}
```

Using the directives also helps with ensuring the cascade works corrcectly - so your custom utilities will be included with the rest of the core utilities layer at the end of the compiled css, and similarly, your components will appear higher up in the stylesheet so thay can still be overridden by the utility classes that follow.

Let me know if that helps.

**Comment by rainypixels** [comment]
Hello again 👋😄 

Ah, ok. That makes sense. I totally missed the layer docs so I appreciate you sharing this idiosyncrasy. That totally fixed it. It took me a second to realize it was fixed because `p-2xs` totally collapses the padding. Probably has something to do with my overrides. 🤦

Thanks, again!

p.s. I found a little bug in `textSizes.js` that I'll file here in a second.

**Comment by rainypixels** [comment]
OK, hate to open this again but I’ve combed through the docs, and I’m still scratching my head. Figured you might have an insight here about some other idiosyncrasy I may be missing unless this is a bug with utopia rule generation...? 😬 Here’s the issue...

The `@layer` suggestion you provided works great for fluid margins, paddings, etc. **except** when I use anything bigger than `xl` (or smaller than `xs`). In other words, this:

```
@layer base {
    h1 {
        @apply mb-xl;
    }
}
```

... compiles to this:

```
h1 {
    margin-bottom: 32px;
    margin-bottom: var(--fs-xl);
}
```
 
... but, this:

```
@layer base {
    h1 {
        @apply mb-2xl;
    }
}
```

... produces this) :

```
   {
	margin-bottom: 48px;
	margin-bottom: var(--fs-2xl);
}
```

Effectively, the `h1` selector is missing and the syntax of the rule is invalid.

![](https://i.kym-cdn.com/photos/images/original/000/173/580/Wat.jpg)

**Comment by chrispymm** [comment]
Ah, ok.  I've run into this issue, and thought I had fixed it. It was related to me incorrectly escaping the keys from the config file.  I have no idea why it does that to the output though! 

Which version of the plugin do you have in your package.json?  If you don't add a version, then it'll default to using master branch, which should *technically* work as all pushes go into master.  But I have it referenced to a tag in my repos.

If you have no version reference you can try running `npm update cwsdigital/tailwind-utopia` which should pull the most recent version.

Alternatively you could update your package.json to have a version tag like so

`"tailwind-utopia": "github:cwsdigital/tailwind-utopia#v1.0.2"`

and then run the `npm update` command.

Hope that sorts things for you.

**Comment by rainypixels** [comment]
That really *is* bizarre output!

I figured it may have been that bug since I combed through your latest commits. I verified that the correct commit [1fc07fc37db8d48e3072d9663314f1f5b4deca99](https://github.com/cwsdigital/tailwind-utopia/commit/1fc07fc37db8d48e3072d9663314f1f5b4deca99) is being pulled down even though the `package-lock.json` shows `1.0.0` (i.e. master has the fix):

```
"node_modules/tailwind-utopia": {
    "version": "1.0.0",
    "resolved": "git+ssh://git@github.com/cwsdigital/tailwind-utopia.git#1fc07fc37db8d48e3072d9663314f1f5b4deca99",
    "dev": true,
    "license": "MIT",
    "peerDependencies": {
        "tailwindcss": "^2"
    }
},
```

I even see the fix in `lib/textSizes.js` in my `node_modules` folder as well. But the bug still persists... 😢

**Comment by chrispymm** [comment]
Hmmm... ok. Strange that the bug is persisting.

Just out interest what version on tailwindcss are you using? As I spotted they released tailwind 2.2.1 (2.21?) which takes JIT mode out of beta, and made some changes to how the watcher works, which on an initial read through I thought could have implications here.

Are you using any other postCSS plugins?

IIRC disabling fallbacks should fix this bug. I know that's not an ideal solution, but it might help in the interim.

I'll try and have an investigate of this next week (and close out the other issue you raised too).

**Comment by rainypixels** [comment]
I'm on tailwindcss 2.2.4. Here's my tailwind config if that helps:

```
{
  "devDependencies": {
    "@markusantonwolf/tailwind-css-plugin-multi-columns": "^1.1.3",
    "autoprefixer": "^10.2.6",
    "browser-sync": "^2.26.14",
    "gulp": "^4.0.2",
    "gulp-imagemin": "^7.1.0",
    "gulp-postcss": "^9.0.0",
    "postcss": "^8.3.5",
    "tailwind-utopia": "cwsdigital/tailwind-utopia#v1.0.2",
    "tailwindcss": "^2.2.2"
  },
  "dependencies": {
    "postcss-import": "^14.0.2"
  },
  "scripts": {
    "dev": "gulp",
    "build": "NODE_ENV=production gulp css",
    "build-images": "gulp images"
  }
}
```

I went ahead and disabled fallback generation, but I'm still seeing the issue. 😿 Let me come back to this in a day or so when I have the ability to focus a little more. I'll just do a fresh install with a simple test case to see if I can repro this. Thanks!

**Comment by chrispymm** [comment]
Hi there,

Apologies that its taken me so long to responding to this.  Not sure whether you've resolved this or not now (or more likely just moved on - my bad!)

I've fixed issue #4 that you raised now, and pushed a new tagged version of 1.0.3

I've also just put together a test setup of the latest everything:

- tailwindcss@2.2.15
- postcss-nested@5.0.6
- postcss@8.3.6

N.B Postcss nested is being used via the new tailwind-nested plugin [as per the docs](https://blog.tailwindcss.com/tailwindcss-2-2#improved-nesting-support)

This is all working for me.

One thought I had, was that if you're in JIT mode it may not regenerate everything on every refresh.  So I vaguely recall that to solve this issue I may have disabled JIT, run a build.  Renabled JIT and then run a build.
